dict_url = {
    '/api/python/page_demo': 'flaskApp.controller.page_demo', 
    '/api/python/login': 'flaskApp.controller.login', 
    '/api/python/menu': 'flaskApp.controller.menu', 
    '/api/python/user_list': 'flaskApp.controller.user_list', 
    '/api/python/role_class': 'flaskApp.controller.role_class', 
    '/api/python/dns_req_list': 'flaskApp.controller.dns_req_list', 
    '/api/python/dns_err_list': 'flaskApp.controller.dns_err_list', 
    '/api/python/top_list': 'flaskApp.controller.top_list', 
    '/api/python/client_type_list': 'flaskApp.controller.client_type_list', 
    '/api/python/dhcp_record_list': 'flaskApp.controller.dhcp_record_list', 
    '/api/python/address_rate_list': 'flaskApp.controller.address_rate_list', 
    '/api/python/operation_list': 'flaskApp.controller.operation_list', 
    '/api/python/device_run_list': 'flaskApp.controller.device_run_list', 
    '/api/python/device_list': 'flaskApp.controller.device_list', 
    '/api/python/power_list': 'flaskApp.controller.power_list', 
    '/api/python/alarm_type_list': 'flaskApp.controller.alarm_type_list', 
    '/api/python/alarm_list': 'flaskApp.controller.alarm_list', 
    '/api/python/email_user_list': 'flaskApp.controller.email_user_list', 
    }